name: Run App for 48 Hours

on:
  workflow_dispatch:

jobs:
  run-part1:
    runs-on: ubuntu-latest
    timeout-minutes: 3  # 设置为 24 小时
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Specify the Python version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # 如果有依赖可以在这里安装
          pip install -r requirements.txt
      - name: Run app.py part 1
        run: python app.py
      - name: Save state
        run: echo "Part 1 completed" > state.txt
      - name: Upload state
        uses: actions/upload-artifact@v2
        with:
          name: state
          path: state.txt

  run-part2:
    needs: run-part1
    runs-on: ubuntu-latest
    timeout-minutes: 1440  # 设置为 24 小时
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Specify the Python version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # 如果有依赖可以在这里安装
          pip install -r requirements.txt
      - name: Download state
        uses: actions/download-artifact@v2
        with:
          name: state
      - name: Check state
        run: cat state.txt
      - name: Run app.py part 2
        run: python app.py
